#!/usr/bin/env python3
"""Layer B authority runner for the CPython primitives ``internal/util`` ports.

``version.parse`` and ``parse_docker_engine_version`` are built on ``int(str)``
and ``str.isdigit()``, and RULINGS.md OQ-14a makes CPython's exact acceptance
sets binding wherever Kathara dispatches on whether a parse raised. Those sets
are properties of the interpreter, not of Kathara, so they are measured here
rather than asserted from documentation:

  * the code points ``int()`` tolerates as surrounding whitespace
  * every code point ``int()`` reads as a decimal digit, and its value
  * the code points ``str.isdigit()`` accepts that ``int()`` rejects
  * ``int()`` and ``repr()`` over a table of awkward literals
  * ``trdparty.strtobool.strtobool``

Result goes to ``internal/util/testdata/pyint/expected.json``, consumed by the
Go table tests in ``internal/util/pyint_test.go``.

The Python behaviour is the truth. When Go disagrees, Go is wrong.

Usage:
    /root/kathara/pyvenv/bin/python tools/vectorcheck/pyint_probe.py
    /root/kathara/pyvenv/bin/python tools/vectorcheck/pyint_probe.py --out PATH
"""

import argparse
import json
import os
import platform
import sys
import unicodedata

KATHARA_SRC = "/root/kathara/kathara-python/src"
if KATHARA_SRC not in sys.path:
    sys.path.insert(0, KATHARA_SRC)

from Kathara.trdparty.strtobool.strtobool import strtobool  # noqa: E402

DEFAULT_OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "internal", "util", "testdata", "pyint", "expected.json",
)

MAX_CODE_POINT = 0x110000


def probe_int_space():
    """Code points ``int()`` strips from both ends of a literal.

    The probe wraps a lone "1" so that neither a sign (``int("+1")`` is 1) nor
    a digit (``int("01")`` is 1) can be mistaken for whitespace.
    """
    accepted = []
    for cp in range(MAX_CODE_POINT):
        ch = chr(cp)
        try:
            if int(ch + "1" + ch) == 1:
                accepted.append(cp)
        except (ValueError, TypeError):
            pass
    return accepted


def probe_digits():
    """Every code point ``int()`` reads as a decimal digit, with its value, and
    every code point ``str.isdigit()`` accepts that ``int()`` does not."""
    decimal = []
    isdigit_only = []
    for cp in range(MAX_CODE_POINT):
        ch = chr(cp)
        value = None
        try:
            parsed = int(ch)
        except (ValueError, TypeError):
            pass
        else:
            if 0 <= parsed <= 9:
                value = parsed
                decimal.append([cp, parsed])
        if ch.isdigit() and value is None:
            isdigit_only.append(cp)
    return decimal, isdigit_only


INT_CASES = [
    "0", "1", "10", "007", "-3", "+3", "  42  ", "\t7\n", "",
    " ", "-", "+", "--1", "1-", "0x1", "0b1", "1e3", "3.0",
    "1_0", "10_000", "_1", "1_", "1__0", "1_0_0", "-1_0", "+1_0",
    "١٢", "٣", "²", "1²", "৩", "一", " 1 ", " 1 ",
    "1", "1", "　1　", "3-beta", "v3", "3 8",
]

REPR_CASES = [
    "", "3-beta", "v3", "it's", 'say "hi"', "both ' and \"",
    "back\\slash", "line\nbreak", "tab\there", "carriage\rreturn",
    "null\x00byte", "bell\x07", "del\x7f", "c1\x85control",
    "caffè", "日本語", "🐳", "١٢", "²",
]

STRTOBOOL_CASES = [
    "y", "yes", "t", "true", "on", "1",
    "Y", "YES", "T", "True", "ON",
    "n", "no", "f", "false", "off", "0",
    "N", "NO", "F", "False", "OFF",
    "", " true", "true ", "2", "yep", "None", "TRUE", "oN", "yEs",
]


def probe_int_cases():
    rows = []
    for literal in INT_CASES:
        row = {"input": literal, "input_hex": literal.encode("utf-8").hex()}
        try:
            row["value"] = int(literal)
        except ValueError as e:
            row["error"] = str(e)
        rows.append(row)
    return rows


def probe_repr_cases():
    return [
        {"input": s, "input_hex": s.encode("utf-8").hex(), "repr": repr(s)}
        for s in REPR_CASES
    ]


def probe_strtobool():
    rows = []
    for literal in STRTOBOOL_CASES:
        row = {"input": literal}
        try:
            row["value"] = bool(strtobool(literal))
        except ValueError as e:
            row["error"] = str(e)
        rows.append(row)
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=DEFAULT_OUT)
    args = ap.parse_args()

    decimal, isdigit_only = probe_digits()
    data = {
        "_comment": (
            "Generated by tools/vectorcheck/pyint_probe.py against the oracle "
            "venv. Do not hand-edit."
        ),
        "python": platform.python_version(),
        "unicode": unicodedata.unidata_version,
        "int_space": probe_int_space(),
        "decimal_digits": decimal,
        "isdigit_only": isdigit_only,
        "int_cases": probe_int_cases(),
        "repr_cases": probe_repr_cases(),
        "strtobool": probe_strtobool(),
    }

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False, sort_keys=False)
        f.write("\n")
    print("wrote %s" % args.out)

    assert data["int_space"], "no whitespace code points"
    assert len(data["decimal_digits"]) > 600, "decimal digit sweep looks short"
    assert data["isdigit_only"], "no isdigit-but-not-int code points"
    assert any("error" in r for r in data["int_cases"]), "no int() errors captured"


if __name__ == "__main__":
    main()
