// Shared test scaffolding: the Python fixtures re-expressed in Go, the fake
// exec transport, and the golden comparison.
//
// The goldens in testdata/ are the 3.8.3 oracle's own
// `ApiClient.sanitize_for_serialization` of the object the Python manager
// submits — the request body, byte for byte — generated by
// `scratchpad/gen_goldens.py`. Nothing here approximates them: the Go object is
// marshaled and compared against that file.

package kubernetes

import (
	"archive/tar"
	"bytes"
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"sync"
	"testing"
	"time"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/watch"
	dynamicfake "k8s.io/client-go/dynamic/fake"
	"k8s.io/client-go/kubernetes/fake"
	k8stesting "k8s.io/client-go/testing"
	"k8s.io/client-go/tools/remotecommand"

	"github.com/KatharaFramework/kathara-go/event"
	"github.com/KatharaFramework/kathara-go/kathara"
	"github.com/KatharaFramework/kathara-go/model"
	"github.com/KatharaFramework/kathara-go/settings"
)

// defaultScenarioHash is `generate_urlsafe_hash("default_scenario")`, the
// namespace every machine fixture deploys into (EXPECTATIONS-k8s "Shared ground
// truth").
const defaultScenarioHash = "FwFaxbiuhvSWb2KpN5zw"

// testSettings is the settings mock every Python `_build_definition` test
// configures (`kubernetes_machine_test.py:272-280`), plus the two keys the
// deploy path reads.
func testSettings() *settings.Settings {
	return &settings.Settings{
		DevicePrefix:      "devprefix",
		NetPrefix:         "netprefix",
		DeviceShell:       "/bin/bash",
		ImagePullPolicy:   ptr("Always"),
		HostShared:        false,
		DockerConfigJSON:  nil,
		VolumeMountPolicy: "Always",
		EnableIPv6:        false,
		PrintStartupLog:   true,
	}
}

func testDefaults(s *settings.Settings) model.Defaults {
	return model.Defaults{
		Image:             "kathara/base",
		DeviceShell:       s.DeviceShell,
		EnableIPv6:        s.EnableIPv6,
		VolumeMountPolicy: s.VolumeMountPolicy,
	}
}

func ptr[T any](v T) *T { return &v }

// fakeClientset names the fake typed clientset once, so the helpers that take
// one read without repeating the import path.
type fakeClientset = fake.Clientset

// testConfig is the [kathara.Config] a Manager is built over in tests.
func testConfig(s *settings.Settings) kathara.Config {
	return kathara.Config{Settings: s, Dispatcher: event.New(), Defaults: testDefaults(s)}
}

// newTestLab is `Lab("default_scenario")`.
func newTestLab(t *testing.T, s *settings.Settings) *model.Lab {
	t.Helper()
	lab := model.NewLab("default_scenario", testDefaults(s))
	if lab.Hash != defaultScenarioHash {
		t.Fatalf("lab hash = %q, want %q", lab.Hash, defaultScenarioHash)
	}
	return lab
}

// newBaseDevice is the `default_device` fixture
// (`kubernetes_machine_test.py:35-46`): the device every Deployment golden is
// built from.
func newBaseDevice(t *testing.T, lab *model.Lab, metas ...[2]string) *model.Machine {
	t.Helper()

	device, err := lab.NewMachine("test_device", nil)
	if err != nil {
		t.Fatalf("NewMachine: %v", err)
	}
	base := [][2]string{
		{"exec", "ls"},
		{"mem", "64m"},
		{"cpus", "2"},
		{"image", "kathara/test"},
		{"bridged", "False"},
	}
	for _, meta := range append(base, metas...) {
		if _, _, err := device.AddMeta(meta[0], meta[1]); err != nil {
			t.Fatalf("AddMeta(%q, %q): %v", meta[0], meta[1], err)
		}
	}
	if _, _, err := device.AddMeta(realNameMeta, "devprefix-test-device-ec84ad3b"); err != nil {
		t.Fatalf("AddMeta(real_name): %v", err)
	}
	return device
}

// newTestManager builds a Manager over a fake clientset, a fake dynamic client
// and a fake exec transport — no cluster, no kubeconfig.
func newTestManager(t *testing.T, s *settings.Settings, objects ...runtime.Object) (*Manager, *fake.Clientset, *dynamicfake.FakeDynamicClient, *fakeExecutor) {
	t.Helper()

	clientset := fake.NewSimpleClientset(objects...)
	dynamicClient := newFakeDynamic()
	executor := &fakeExecutor{}

	m := newManager(testConfig(s), clientset, dynamicClient, executor, "user123")
	m.machine.portName = func() string { return "0123456789abcde" }
	// The real watchdogs are 180 s. A test that deploys devices must inject the
	// Ready events a cluster would send ([injectPodsReady]), and one that
	// undeploys must inject the DELETED events ([injectPodsDeleted]); this makes
	// the one that forgets fail in seconds instead of hanging for three minutes.
	m.machine.startupTimeout = 5 * time.Second
	m.machine.shutdownTimeout = 5 * time.Second

	return m, clientset, dynamicClient, executor
}

// newFakeDynamic builds the dynamic client for NetworkAttachmentDefinitions.
//
// Two details of the fake are worth stating, because getting either wrong makes
// every listing come back empty:
//
//   - the CRD is in no built-in scheme, so its LIST kind has to be declared
//     against [netGVR] or the tracker cannot build a result;
//   - objects may NOT be handed to the constructor. It stores them under the
//     resource `UnsafeGuessKindToResource` derives from the kind, which for
//     `NetworkAttachmentDefinition` is `networkattachmentdefinitions` — and the
//     real plural is `network-attachment-definitions`. They go through
//     `Tracker().Create`, which takes the resource explicitly.
func newFakeDynamic(objects ...*Network) *dynamicfake.FakeDynamicClient {
	scheme := runtime.NewScheme()
	listKinds := map[schema.GroupVersionResource]string{
		netGVR: netKind + "List",
	}
	client := dynamicfake.NewSimpleDynamicClientWithCustomListKinds(scheme, listKinds)
	for _, object := range objects {
		if err := client.Tracker().Create(netGVR, object, object.GetNamespace()); err != nil {
			panic(err)
		}
	}
	return client
}

// newTestNetwork is a deployed NetworkAttachmentDefinition, as
// `KubernetesLink.create` leaves it in `link.api_object`.
func newTestNetwork(namespace, linkName string, networkID int) *Network {
	network := NetworkDefinition(NetworkName("netprefix", linkName), linkName, namespace, networkID)
	network.SetNamespace(namespace)
	return network
}

// newTestPod is a pod as `get_machines_api_objects_by_filters` returns one.
func newTestPod(namespace, machineName string, attachments ...podNetworkAttachment) *corev1.Pod {
	return &corev1.Pod{
		ObjectMeta: podMeta(namespace, machineName, attachments...),
		Spec: corev1.PodSpec{
			NodeName: "node-1",
			Containers: []corev1.Container{{
				Name:  DeploymentName("devprefix", machineName),
				Image: "kathara/test",
				Env:   []corev1.EnvVar{{Name: megalosShellEnv, Value: "/bin/bash"}},
			}},
		},
		Status: corev1.PodStatus{Phase: corev1.PodRunning},
	}
}

func podMeta(namespace, machineName string, attachments ...podNetworkAttachment) metav1.ObjectMeta {
	return metav1.ObjectMeta{
		Name:      DeploymentName("devprefix", machineName) + "-abcde",
		Namespace: namespace,
		Labels:    ObjectLabels(machineName),
		Annotations: map[string]string{
			networkAttachmentAnnotation: encodeNetworkAttachments(attachments),
		},
	}
}

// injectPodsReady registers a pod watch reactor carrying one Ready event per
// device, which is what the API server reports once the pods come up — and what
// `_wait_machines_startup` counts (`KubernetesMachine.py:256-260`).
//
// The fake tracker reports only changes made AFTER a watcher is registered, and
// the events a deploy waits for are produced by the cluster rather than by the
// client, so they have to be injected.
func injectPodsReady(clientset *fakeClientset, namespace string, machineNames ...string) {
	watcher := watch.NewFakeWithChanSize(len(machineNames), false)
	for _, name := range machineNames {
		pod := newTestPod(namespace, name)
		pod.Status.ContainerStatuses = []corev1.ContainerStatus{{Ready: true, Image: "kathara/test"}}
		watcher.Modify(pod)
	}
	clientset.PrependWatchReactor("pods", k8stesting.DefaultWatchReactor(watcher, nil))
}

// injectPodsDeleted is the undeploy twin of [injectPodsReady]: one DELETED pod
// event per device, which is what `_wait_machines_shutdown` counts
// (`KubernetesMachine.py:627-634`) and what `undeploy`'s `wait_thread.join()`
// blocks on.
//
// A test that deletes pods without calling it does not fail on an assertion; it
// waits out `machineService.shutdownTimeout`, which [newTestManager] shortens
// for exactly that reason.
func injectPodsDeleted(clientset *fakeClientset, namespace string, machineNames ...string) {
	injectPodsDeletedAfter(clientset, 0, namespace, machineNames...)
}

// injectPodsDeletedAfter is [injectPodsDeleted] with the events held back for
// delay, which is what a cluster does: the DELETED events land seconds after
// `delete_namespaced_deployment` has returned.
//
// The delay is what makes a test able to tell a call that JOINS the shutdown
// watcher from one that abandons it — with events already queued, a call that
// cancels the watcher immediately after the fan-out still sees them and the
// difference is invisible.
func injectPodsDeletedAfter(clientset *fakeClientset, delay time.Duration, namespace string, machineNames ...string) {
	events := make([]watch.Event, 0, len(machineNames))
	for _, name := range machineNames {
		events = append(events, watch.Event{Type: watch.Deleted, Object: newTestPod(namespace, name)})
	}
	clientset.PrependWatchReactor("pods", k8stesting.DefaultWatchReactor(newDelayedWatcher(delay, events), nil))
}

// delayedWatcher is a [watch.Interface] over a fixed script of events, none of
// which is delivered before delay has passed.
//
// It is not `watch.NewFakeWithChanSize`, whose `Stop` closes the result channel
// and turns a late send into a panic; here Stop only signals, so a test may
// abandon the watcher without taking the process down.
type delayedWatcher struct {
	events chan watch.Event
	stop   chan struct{}
	once   sync.Once
}

func newDelayedWatcher(delay time.Duration, events []watch.Event) *delayedWatcher {
	w := &delayedWatcher{events: make(chan watch.Event), stop: make(chan struct{})}

	go func() {
		defer close(w.events)

		if delay > 0 {
			timer := time.NewTimer(delay)
			defer timer.Stop()
			select {
			case <-timer.C:
			case <-w.stop:
				return
			}
		}

		for _, ev := range events {
			select {
			case w.events <- ev:
			case <-w.stop:
				return
			}
		}
	}()

	return w
}

func (w *delayedWatcher) Stop() { w.once.Do(func() { close(w.stop) }) }

func (w *delayedWatcher) ResultChan() <-chan watch.Event { return w.events }

// newTestDeployment is the Deployment behind a pod, which the undeploy path
// deletes by name.
func newTestDeployment(namespace, machineName string) *appsv1.Deployment {
	return &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{
			Name:      DeploymentName("devprefix", machineName),
			Namespace: namespace,
			Labels:    ObjectLabels(machineName),
		},
	}
}

// ---------------------------------------------------------------------------
// Fake exec transport
// ---------------------------------------------------------------------------

// fakeExecutor records every [execRequest] and replays a canned response, which
// is how the exec, copy, retrieve and TTY paths are exercised without a cluster.
type fakeExecutor struct {
	// mu guards requests: the undeploy fan-out builds one executor per worker
	// goroutine, so the recorder has to be safe for concurrent use.
	mu       sync.Mutex
	requests []execRequest

	// stdout and stderr are written to the corresponding streams.
	stdout []byte
	stderr []byte
	// stdin, if non-nil, receives whatever the caller wrote.
	stdin *[]byte
	// err is what StreamWithContext answers — nil, a
	// [utilexec.CodeExitError], or a plain error carrying the API server's
	// Status message.
	err error
	// newErr fails the executor construction itself.
	newErr error
	// block, when non-nil, is waited on before the stream returns, so a test
	// can observe a stream that has not finished.
	block chan struct{}
}

func (f *fakeExecutor) NewExecutor(req execRequest) (remotecommand.Executor, error) {
	f.mu.Lock()
	f.requests = append(f.requests, req)
	f.mu.Unlock()
	if f.newErr != nil {
		return nil, f.newErr
	}
	return &fakeStream{owner: f}, nil
}

func (f *fakeExecutor) lastRequest(t *testing.T) execRequest {
	t.Helper()
	f.mu.Lock()
	defer f.mu.Unlock()
	if len(f.requests) == 0 {
		t.Fatal("no exec request was made")
	}
	return f.requests[len(f.requests)-1]
}

type fakeStream struct{ owner *fakeExecutor }

func (s *fakeStream) Stream(options remotecommand.StreamOptions) error {
	return s.StreamWithContext(context.Background(), options)
}

func (s *fakeStream) StreamWithContext(ctx context.Context, options remotecommand.StreamOptions) error {
	s.owner.mu.Lock()
	defer s.owner.mu.Unlock()

	if options.Stdin != nil && s.owner.stdin != nil {
		buf := make([]byte, 0, 4096)
		chunk := make([]byte, 4096)
		for {
			n, err := options.Stdin.Read(chunk)
			buf = append(buf, chunk[:n]...)
			if err != nil {
				break
			}
		}
		*s.owner.stdin = buf
	}
	if options.Stdout != nil && len(s.owner.stdout) > 0 {
		if _, err := options.Stdout.Write(s.owner.stdout); err != nil {
			return err
		}
	}
	if options.Stderr != nil && len(s.owner.stderr) > 0 {
		if _, err := options.Stderr.Write(s.owner.stderr); err != nil {
			return err
		}
	}
	if s.owner.block != nil {
		select {
		case <-s.owner.block:
		case <-ctx.Done():
			return ctx.Err()
		}
	}
	return s.owner.err
}

// corev1EnvVar builds the single-element env slice the shell-fallback table
// wants.
func corev1EnvVar(name, value string) corev1.EnvVar {
	return corev1.EnvVar{Name: name, Value: value}
}

// tarWithFile is a one-member uncompressed tar, which is what `tar cf -` writes
// to the exec's stdout on the retrieve path.
func tarWithFile(t *testing.T, name, content string) []byte {
	t.Helper()

	var buf bytes.Buffer
	tw := tar.NewWriter(&buf)
	if err := tw.WriteHeader(&tar.Header{
		Name:     name,
		Typeflag: tar.TypeReg,
		Size:     int64(len(content)),
		Mode:     0o644,
	}); err != nil {
		t.Fatalf("tar header: %v", err)
	}
	if _, err := tw.Write([]byte(content)); err != nil {
		t.Fatalf("tar write: %v", err)
	}
	if err := tw.Close(); err != nil {
		t.Fatalf("tar close: %v", err)
	}
	return buf.Bytes()
}

// readFile is os.ReadFile as a string, for the extraction assertions.
func readFile(path string) (string, error) {
	raw, err := os.ReadFile(path)
	return string(raw), err
}

// ---------------------------------------------------------------------------
// Golden comparison
// ---------------------------------------------------------------------------

// assertGolden compares obj against testdata/name.
//
// # Why the golden is decoded before it is compared
//
// The two clients serialize the same object differently, and none of the
// differences carry information:
//
//   - the Python client drops only `None` attributes, while client-go's structs
//     carry `omitempty` and additionally drop empty slices, empty maps and
//     `false` — so Python emits `volumeMounts: []`, `volumes: []`,
//     `imagePullSecrets: []` and `readOnly: false` where Go emits nothing;
//   - client-go's `metav1` types emit `creationTimestamp: null` and
//     `status: {}`, which the Python client has no field for;
//   - `resource.Quantity` re-serializes canonically, so the `2000m` CPU limit
//     Python sends is `2` here — the same quantity, and the same thing the API
//     server stores whichever client posted it.
//
// So the golden is DECODED INTO THE SAME GO TYPE and re-encoded, which puts
// both sides through one serializer; what is then compared byte for byte is
// "the Kubernetes object 3.8.3 submits" against "the Kubernetes object this
// package submits".
//
// A decode that silently dropped a field would make that comparison vacuous, so
// [assertRoundTrip] additionally checks that every key of the raw golden
// survives the decode — except where its value is a zero the Go encoder is
// entitled to omit.
//
// The pair is recorded in DIVERGENCES.md so the difference is stated once
// rather than assumed.
func assertGolden(t *testing.T, name string, obj any, replacements ...[2]string) {
	t.Helper()

	goldenRaw, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	goldenText := string(goldenRaw)
	for _, replacement := range replacements {
		goldenText = strings.ReplaceAll(goldenText, replacement[0], replacement[1])
	}

	decoded := reflect.New(reflect.TypeOf(obj).Elem()).Interface()
	if err := json.Unmarshal([]byte(goldenText), decoded); err != nil {
		t.Fatalf("decode golden into %T: %v", obj, err)
	}
	assertRoundTrip(t, name, goldenText, decoded)

	got := mustMarshalIndent(t, obj)
	want := mustMarshalIndent(t, decoded)
	if got != want {
		t.Errorf("object does not match testdata/%s\n--- got ---\n%s\n--- want ---\n%s", name, got, want)
	}
}

// assertRoundTrip is the guard on [assertGolden]'s decode: every key the oracle
// emitted must still be there after the golden has been through the Go type.
//
// A key whose raw value is null, false, 0, an empty array or an empty object is
// allowed to vanish, because that is exactly what `omitempty` removes and none
// of those five carries information at the API server.
func assertRoundTrip(t *testing.T, name, rawText string, decoded any) {
	t.Helper()

	var raw, back any
	if err := json.Unmarshal([]byte(rawText), &raw); err != nil {
		t.Fatalf("unmarshal golden: %v", err)
	}
	reencoded, err := json.Marshal(decoded)
	if err != nil {
		t.Fatalf("re-encode golden: %v", err)
	}
	if err := json.Unmarshal(reencoded, &back); err != nil {
		t.Fatalf("unmarshal re-encoded golden: %v", err)
	}

	for _, path := range missingKeyPaths("", raw, back) {
		t.Errorf("testdata/%s: key %s did not survive the decode into the Go type", name, path)
	}
}

// missingKeyPaths reports the key paths present in raw and absent from back,
// skipping the omittable zeros.
func missingKeyPaths(prefix string, raw, back any) []string {
	var missing []string

	switch value := raw.(type) {
	case map[string]any:
		other, _ := back.(map[string]any)
		for key, rawChild := range value {
			path := prefix + "." + key
			backChild, present := other[key]
			if !present {
				if !isOmittable(rawChild) {
					missing = append(missing, path)
				}
				continue
			}
			missing = append(missing, missingKeyPaths(path, rawChild, backChild)...)
		}
	case []any:
		other, _ := back.([]any)
		for i, rawChild := range value {
			if i >= len(other) {
				missing = append(missing, prefix+"["+strconv.Itoa(i)+"]")
				continue
			}
			missing = append(missing, missingKeyPaths(prefix+"["+strconv.Itoa(i)+"]", rawChild, other[i])...)
		}
	}

	sort.Strings(missing)
	return missing
}

// isOmittable is the five shapes `omitempty` drops.
func isOmittable(v any) bool {
	switch value := v.(type) {
	case nil:
		return true
	case bool:
		return !value
	case float64:
		return value == 0
	case string:
		return value == ""
	case []any:
		return len(value) == 0
	case map[string]any:
		return len(value) == 0
	default:
		return false
	}
}

func mustMarshalIndent(t *testing.T, v any) string {
	t.Helper()
	raw, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	return string(raw)
}
