// Code generated by tools/vectorcheck/gen_encoding_tables.py. DO NOT EDIT.
// Transpiled from binaryornot 0.6.0's tree.py, itself generated by
// binaryornot's scripts/train_detector.py. Thresholds are copied verbatim.

package util

// binaryDecisionTree is binaryornot.tree.is_binary: the trained classifier
// over the 24-element feature vector computeBinaryFeatures produces.
func binaryDecisionTree(f *[binaryFeatureCount]float64) bool {
	if f[1] <= 0.000977 {
		if f[17] <= 0.000977 {
			if f[4] <= 0.500000 {
				if f[22] <= 0.500000 {
					if f[7] <= 1.953445 {
						return true
					} else {
						if f[7] <= 2.749470 {
							return false
						} else {
							if f[14] <= 0.500000 {
								return true
							} else {
								return true
							}
						}
					}
				} else {
					return false
				}
			} else {
				return false
			}
		} else {
			if f[4] <= 0.500000 {
				if f[17] <= 0.063636 {
					if f[7] <= 2.021329 {
						return true
					} else {
						if f[13] <= 0.500000 {
							return false
						} else {
							return false
						}
					}
				} else {
					if f[7] <= 3.047898 {
						return false
					} else {
						if f[2] <= 0.758706 {
							if f[17] <= 0.134848 {
								if f[3] <= 0.633612 {
									if f[7] <= 3.851786 {
										return false
									} else {
										if f[3] <= 0.483333 {
											return false
										} else {
											if f[17] <= 0.129167 {
												return true
											} else {
												return false
											}
										}
									}
								} else {
									if f[2] <= 0.145455 {
										return false
									} else {
										return true
									}
								}
							} else {
								if f[19] <= 0.500000 {
									if f[7] <= 3.572021 {
										if f[3] <= 0.490000 {
											if f[2] <= 0.651515 {
												return false
											} else {
												return true
											}
										} else {
											if f[7] <= 3.370112 {
												return true
											} else {
												if f[3] <= 0.651515 {
													if f[17] <= 0.318182 {
														return true
													} else {
														return true
													}
												} else {
													return true
												}
											}
										}
									} else {
										if f[2] <= 0.615079 {
											if f[20] <= 0.500000 {
												if f[13] <= 0.500000 {
													return true
												} else {
													return true
												}
											} else {
												if f[17] <= 0.176923 {
													return false
												} else {
													return true
												}
											}
										} else {
											if f[17] <= 0.252381 {
												return false
											} else {
												return true
											}
										}
									}
								} else {
									if f[7] <= 3.889752 {
										return true
									} else {
										return false
									}
								}
							}
						} else {
							return false
						}
					}
				}
			} else {
				return false
			}
		}
	} else {
		if f[0] <= 0.163978 {
			if f[4] <= 0.500000 {
				if f[7] <= 3.264621 {
					if f[17] <= 0.022678 {
						if f[2] <= 0.000977 {
							if f[5] <= 0.001953 {
								return false
							} else {
								return true
							}
						} else {
							return true
						}
					} else {
						if f[1] <= 0.095455 {
							if f[17] <= 0.306818 {
								if f[1] <= 0.055728 {
									return false
								} else {
									return false
								}
							} else {
								return true
							}
						} else {
							return false
						}
					}
				} else {
					if f[10] <= 0.500000 {
						if f[2] <= 0.455534 {
							if f[3] <= 0.790570 {
								if f[1] <= 0.485714 {
									if f[7] <= 3.540884 {
										if f[7] <= 3.528408 {
											if f[2] <= 0.316667 {
												if f[2] <= 0.286364 {
													if f[17] <= 0.095455 {
														return true
													} else {
														return true
													}
												} else {
													if f[13] <= 0.500000 {
														return false
													} else {
														return true
													}
												}
											} else {
												return true
											}
										} else {
											return false
										}
									} else {
										if f[2] <= 0.446657 {
											return true
										} else {
											if f[17] <= 0.066638 {
												if f[2] <= 0.450099 {
													return false
												} else {
													return true
												}
											} else {
												return true
											}
										}
									}
								} else {
									return false
								}
							} else {
								return false
							}
						} else {
							if f[3] <= 0.425959 {
								if f[3] <= 0.394552 {
									if f[7] <= 4.209417 {
										if f[7] <= 4.175213 {
											if f[3] <= 0.100962 {
												return false
											} else {
												if f[3] <= 0.248047 {
													return true
												} else {
													if f[17] <= 0.106443 {
														return false
													} else {
														return true
													}
												}
											}
										} else {
											return false
										}
									} else {
										if f[23] <= 0.500000 {
											return true
										} else {
											return true
										}
									}
								} else {
									if f[17] <= 0.082906 {
										return false
									} else {
										if f[1] <= 0.025000 {
											return false
										} else {
											if f[7] <= 3.520764 {
												return false
											} else {
												if f[1] <= 0.122500 {
													return true
												} else {
													if f[0] <= 0.033333 {
														return false
													} else {
														return true
													}
												}
											}
										}
									}
								}
							} else {
								if f[17] <= 0.098599 {
									if f[1] <= 0.012902 {
										return true
									} else {
										if f[23] <= 0.500000 {
											return false
										} else {
											if f[3] <= 0.458087 {
												return true
											} else {
												return true
											}
										}
									}
								} else {
									if f[7] <= 4.453697 {
										if f[3] <= 0.472136 {
											if f[17] <= 0.121324 {
												return false
											} else {
												if f[17] <= 0.302885 {
													if f[7] <= 3.539612 {
														return false
													} else {
														return true
													}
												} else {
													return false
												}
											}
										} else {
											return true
										}
									} else {
										return true
									}
								}
							}
						}
					} else {
						if f[14] <= 0.500000 {
							return false
						} else {
							return false
						}
					}
				}
			} else {
				if f[1] <= 0.450000 {
					if f[1] <= 0.006212 {
						return true
					} else {
						return false
					}
				} else {
					return true
				}
			}
		} else {
			if f[23] <= 0.500000 {
				if f[3] <= 0.082843 {
					if f[6] <= 0.282534 {
						return false
					} else {
						if f[7] <= 3.088801 {
							if f[0] <= 0.822852 {
								if f[2] <= 0.291667 {
									return false
								} else {
									if f[1] <= 0.521739 {
										return false
									} else {
										return true
									}
								}
							} else {
								if f[16] <= 0.500000 {
									return true
								} else {
									return true
								}
							}
						} else {
							if f[5] <= 0.140625 {
								return false
							} else {
								return true
							}
						}
					}
				} else {
					if f[17] <= 0.291667 {
						if f[7] <= 0.698576 {
							return true
						} else {
							if f[7] <= 5.613847 {
								if f[2] <= 0.361264 {
									if f[20] <= 0.500000 {
										return false
									} else {
										if f[14] <= 0.500000 {
											if f[0] <= 0.379808 {
												return false
											} else {
												return true
											}
										} else {
											return false
										}
									}
								} else {
									if f[2] <= 0.408333 {
										if f[1] <= 0.260000 {
											return false
										} else {
											return true
										}
									} else {
										return false
									}
								}
							} else {
								if f[17] <= 0.012485 {
									return false
								} else {
									return true
								}
							}
						}
					} else {
						return true
					}
				}
			} else {
				if f[20] <= 0.500000 {
					return true
				} else {
					return true
				}
			}
		}
	}
}
