package util

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"sync"
	"testing"
)

// The fixture is generated by
//	/root/kathara/pyvenv/bin/python tools/vectorcheck/pyint_probe.py

type pyintFixture struct {
	Python        string          `json:"python"`
	Unicode       string          `json:"unicode"`
	IntSpace      []rune          `json:"int_space"`
	DecimalDigits [][2]int        `json:"decimal_digits"`
	IsDigitOnly   []rune          `json:"isdigit_only"`
	IntCases      []pyIntCase     `json:"int_cases"`
	ReprCases     []pyReprCase    `json:"repr_cases"`
	StrToBool     []strToBoolCase `json:"strtobool"`
}

type pyIntCase struct {
	Input string `json:"input"`
	Hex   string `json:"input_hex"`
	Value *int   `json:"value"`
	Error string `json:"error"`
}

type pyReprCase struct {
	Input string `json:"input"`
	Hex   string `json:"input_hex"`
	Repr  string `json:"repr"`
}

type strToBoolCase struct {
	Input string `json:"input"`
	Value *bool  `json:"value"`
	Error string `json:"error"`
}

var (
	pyintOnce sync.Once
	pyintData pyintFixture
	pyintErr  error
)

func loadPyintFixture(t *testing.T) *pyintFixture {
	t.Helper()

	pyintOnce.Do(func() {
		raw, err := os.ReadFile(filepath.Join("testdata", "pyint", "expected.json"))
		if err != nil {
			pyintErr = err
			return
		}
		pyintErr = json.Unmarshal(raw, &pyintData)
	})
	if pyintErr != nil {
		t.Fatalf("loading testdata/pyint/expected.json: %v", pyintErr)
	}

	return &pyintData
}

// TestIntSpaceIsExact checks the whitespace set both ways: every code point
// CPython strips must be stripped here, and no other code point may be.
func TestIntSpaceIsExact(t *testing.T) {
	fixture := loadPyintFixture(t)

	accepted := make(map[rune]bool, len(fixture.IntSpace))
	for _, cp := range fixture.IntSpace {
		accepted[cp] = true
		if !intSpace(cp) {
			t.Errorf("U+%04X is stripped by int() and is not in intSpace", cp)
		}
	}

	for cp := rune(0); cp < 0x110000; cp++ {
		if intSpace(cp) && !accepted[cp] {
			t.Errorf("U+%04X is in intSpace and is not stripped by int()", cp)
		}
	}

	for _, cp := range []rune{0x1C, 0x1D, 0x1E, 0x1F} {
		if intSpace(cp) {
			t.Errorf("U+%04X is strip()-able but int() rejects it", cp)
		}
		if !asciiSpace(byte(cp)) {
			t.Errorf("U+%04X must still be whitespace to Slug", cp)
		}
	}
}

// TestDecimalValueIsExact checks every code point CPython's int() reads as a
// digit and its value, including the Arabic-Indic digit used by lab files.
func TestDecimalValueIsExact(t *testing.T) {
	fixture := loadPyintFixture(t)

	if len(fixture.DecimalDigits) < 600 {
		t.Fatalf("only %d decimal digits in the fixture; it looks truncated", len(fixture.DecimalDigits))
	}

	known := make(map[rune]int, len(fixture.DecimalDigits))
	for _, row := range fixture.DecimalDigits {
		cp, want := rune(row[0]), row[1]
		known[cp] = want

		got, ok := decimalValue(cp)
		if !ok {
			t.Errorf("U+%04X is a decimal digit worth %d and decimalValue rejects it", cp, want)
			continue
		}
		if got != want {
			t.Errorf("decimalValue(U+%04X) = %d, oracle says %d", cp, got, want)
		}
	}

	for cp := rune(0); cp < 0x110000; cp++ {
		if _, ok := decimalValue(cp); ok {
			if _, isKnown := known[cp]; !isKnown {
				t.Errorf("decimalValue accepts U+%04X, which int() does not", cp)
			}
		}
	}
}

// TestPyIsDigitIsExact checks `str.isdigit()`, which is wider than `int()`
// accepts. The gap is load-bearing exactly once, in
// [ParseDockerEngineVersion], which keeps a character because isdigit says yes
// and then hands it to a parse that says no.
func TestPyIsDigitIsExact(t *testing.T) {
	fixture := loadPyintFixture(t)

	isDigit := make(map[rune]bool, len(fixture.DecimalDigits)+len(fixture.IsDigitOnly))
	for _, row := range fixture.DecimalDigits {
		isDigit[rune(row[0])] = true
	}
	for _, cp := range fixture.IsDigitOnly {
		isDigit[cp] = true
		if _, ok := decimalValue(cp); ok {
			t.Errorf("U+%04X is isdigit-only and decimalValue accepts it", cp)
		}
	}

	for cp := rune(0); cp < 0x110000; cp++ {
		if got := PyIsDigit(cp); got != isDigit[cp] {
			t.Errorf("PyIsDigit(U+%04X) = %v, oracle says %v", cp, got, isDigit[cp])
		}
	}

	// The superscript two is the canonical member of the gap.
	if !PyIsDigit('²') {
		t.Error("PyIsDigit('²') = false")
	}
	if _, err := PyInt("²"); !errors.Is(err, ErrPyIntSyntax) {
		t.Errorf("PyInt(\"²\") must be a syntax error, got %v", err)
	}
}

func TestPyInt(t *testing.T) {
	for _, tc := range loadPyintFixture(t).IntCases {
		t.Run(tc.Hex, func(t *testing.T) {
			got, err := PyInt(tc.Input)

			if tc.Error != "" {
				if err == nil {
					t.Fatalf("PyInt(%q) = %d, oracle raised ValueError: %s", tc.Input, got, tc.Error)
				}
				if !errors.Is(err, ErrPyIntSyntax) {
					t.Fatalf("PyInt(%q) error = %v, want ErrPyIntSyntax", tc.Input, err)
				}
				if rendered := PyIntFailure(err, tc.Input).Error(); rendered != tc.Error {
					t.Errorf("PyIntFailure = %q, oracle says %q", rendered, tc.Error)
				}
				return
			}
			if err != nil {
				t.Fatalf("PyInt(%q): %v", tc.Input, err)
			}
			if tc.Value == nil {
				t.Fatalf("fixture for %q has neither a value nor an error", tc.Input)
			}
			if got != *tc.Value {
				t.Errorf("PyInt(%q) = %d, oracle says %d", tc.Input, got, *tc.Value)
			}
		})
	}
}

// TestPyIntUnderscoreRule pins PEP 515 as CPython implements it, because the
// CPython-compatible parsing treats underscores as interface-number syntax.
// digit on both sides, so `0_1` is interface 1 while `_0` and `0_` are not
// interface numbers at all and fall through to the meta path.
func TestPyIntUnderscoreRule(t *testing.T) {
	for _, tc := range []struct {
		input string
		value int
		ok    bool
	}{
		{"1_0", 10, true},
		{"0_1", 1, true},
		{"1_0_0", 100, true},
		{"-1_0", -10, true},
		{"_1", 0, false},
		{"1_", 0, false},
		{"1__0", 0, false},
		{"_", 0, false},
	} {
		got, err := PyInt(tc.input)
		if tc.ok {
			if err != nil {
				t.Errorf("PyInt(%q): %v", tc.input, err)
				continue
			}
			if got != tc.value {
				t.Errorf("PyInt(%q) = %d, want %d", tc.input, got, tc.value)
			}
			continue
		}
		if !errors.Is(err, ErrPyIntSyntax) {
			t.Errorf("PyInt(%q) = (%d, %v), want a syntax error", tc.input, got, err)
		}
	}
}

func TestPyIntRangeIsBounded(t *testing.T) {
	for _, literal := range []string{
		"99999999999999999999999999",
		"99999999999999999999",
		"9223372036854775808", // math.MaxInt64 + 1
		"-9999999999999999999999",
	} {
		_, err := PyInt(literal)
		if !errors.Is(err, ErrPyIntRange) {
			t.Errorf("PyInt(%q) = %v, want ErrPyIntRange", literal, err)
		}
		if errors.Is(err, ErrPyIntSyntax) {
			t.Errorf("PyInt(%q) must not look like a syntax error", literal)
		}
	}
}

func TestPythonRepr(t *testing.T) {
	for _, tc := range loadPyintFixture(t).ReprCases {
		t.Run(tc.Hex, func(t *testing.T) {
			if got := PythonRepr(tc.Input); got != tc.Repr {
				t.Errorf("PythonRepr(%q) = %s, oracle says %s", tc.Input, got, tc.Repr)
			}
		})
	}
}

// TestPythonReprQuoteChoice pins the one asymmetry in the quoting rule:
// CPython switches to double quotes only when the string contains a single
// quote and no double quote.
func TestPythonReprQuoteChoice(t *testing.T) {
	for _, tc := range []struct {
		input string
		want  string
	}{
		{`plain`, `'plain'`},
		{`it's`, `"it's"`},
		{`say "hi"`, `'say "hi"'`},
		{`both ' and "`, `'both \' and "'`},
	} {
		if got := PythonRepr(tc.input); got != tc.want {
			t.Errorf("PythonRepr(%q) = %s, want %s", tc.input, got, tc.want)
		}
	}
}

func TestStrToBool(t *testing.T) {
	for _, tc := range loadPyintFixture(t).StrToBool {
		t.Run(tc.Input, func(t *testing.T) {
			got, err := StrToBool(tc.Input)

			if tc.Error != "" {
				if err == nil {
					t.Fatalf("StrToBool(%q) = %v, oracle raised %s", tc.Input, got, tc.Error)
				}
				if err.Error() != tc.Error {
					t.Errorf("StrToBool(%q) error = %q, oracle says %q", tc.Input, err, tc.Error)
				}
				return
			}
			if err != nil {
				t.Fatalf("StrToBool(%q): %v", tc.Input, err)
			}
			if tc.Value == nil {
				t.Fatalf("fixture for %q has neither a value nor an error", tc.Input)
			}
			if got != *tc.Value {
				t.Errorf("StrToBool(%q) = %v, oracle says %v", tc.Input, got, *tc.Value)
			}
		})
	}
}

// TestStrToBoolQuotesTheFoldedValue pins the detail a user sees: the message
// echoes the lower-cased value, not what was typed.
func TestStrToBoolQuotesTheFoldedValue(t *testing.T) {
	_, err := StrToBool("YEP")
	if err == nil {
		t.Fatal("\"YEP\" must be an error")
	}
	if err.Error() != "Invalid truth value `yep`." {
		t.Errorf("error = %q", err)
	}
}

// TestPythonStrListRepr pins `str(list)` for the two backends' `connect` and
// `exec` debug lines, whose `%s` operand is a `shlex.split` result and so
// renders as a Python list and not as the words joined
// (`DockerMachine.py:677,777`, `KubernetesMachine.py:727,817`).
func TestPythonStrListRepr(t *testing.T) {
	tests := []struct {
		name  string
		items []string
		want  string
	}{
		{"nil", nil, "[]"},
		{"empty", []string{}, "[]"},
		{"one word", []string{"/bin/bash"}, "['/bin/bash']"},
		{"two words", []string{"/bin/sh", "-l"}, "['/bin/sh', '-l']"},
		{"embedded quote", []string{"it's"}, `["it's"]`},
		{"embedded newline", []string{"a\nb"}, `['a\nb']`},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := PythonStrListRepr(tc.items); got != tc.want {
				t.Errorf("PythonStrListRepr(%q) = %q, want %q", tc.items, got, tc.want)
			}
		})
	}
}
