package util

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"testing"

	"github.com/KatharaFramework/kathara-go/kerrors"
)

// The fixture is generated by
//	/root/kathara/pyvenv/bin/python tools/vectorcheck/utils_probe.py
// against the 3.8.3 source tree in the oracle venv. Every table below reads it
// rather than restating the expected values, so a regenerated fixture is the
// only way the expectations move. Differences require review.

type utilsFixture struct {
	Python                 string          `json:"python"`
	KatharaVersion         string          `json:"kathara_version"`
	Live                   liveFixture     `json:"live"`
	HumanReadableBytes     []hrbCase       `json:"human_readable_bytes"`
	HumanReadableBytesBulk [][2]string     `json:"human_readable_bytes_bulk"`
	Version                versionFixture  `json:"version"`
	Architecture           archFixture     `json:"architecture"`
	CDMac                  []cdMacCase     `json:"cd_mac"`
	CheckVars              []checkVarCase  `json:"check_vars"`
	ReSearchFail           []reCase        `json:"re_search_fail"`
	Realpath               []realpathCase  `json:"realpath"`
	Permissions            permsFixture    `json:"permissions"`
	PermsUnprivileged      *permsFixture   `json:"permissions_unprivileged"`
	ExecutablePath         []execCase      `json:"executable_path"`
	Which                  []whichCase     `json:"which"`
	NTPath                 ntpathFixture   `json:"ntpath"`
	URLSafeHash            []stringCase    `json:"urlsafe_hash"`
	Slug                   []stringCase    `json:"slug"`
	UserNameChain          []chainCase     `json:"user_name_chain"`
	SlugNFKDSweep          []nfkdSweepCase `json:"slug_nfkd_sweep"`
}

type liveFixture struct {
	Platform             string   `json:"platform"`
	Node                 string   `json:"node"`
	PwName               string   `json:"pw_name"`
	PwUID                int      `json:"pw_uid"`
	PwGID                int      `json:"pw_gid"`
	PwDir                string   `json:"pw_dir"`
	SudoUID              *string  `json:"sudo_uid"`
	HomeEnv              *string  `json:"home_env"`
	UID                  int      `json:"uid"`
	GID                  int      `json:"gid"`
	OsGetuid             int      `json:"os_getuid"`
	CurrentUserName      string   `json:"current_user_name"`
	CurrentUserHome      string   `json:"current_user_home"`
	IsAdmin              bool     `json:"is_admin"`
	IsWSL                bool     `json:"is_wsl"`
	PoolSize             int      `json:"pool_size"`
	UnameRelease         string   `json:"uname_release"`
	ReservedMachineNames []string `json:"reserved_machine_names"`
	ExcludedFiles        []string `json:"excluded_files"`
	Architecture         string   `json:"architecture"`
}

type stringCase struct {
	Input  string `json:"input"`
	Hex    string `json:"input_hex"`
	Output string `json:"output"`
}

type chainCase struct {
	Username     string `json:"username"`
	Hostname     string `json:"hostname"`
	HostnameHash string `json:"hostname_hash"`
	Output       string `json:"output"`
}

// nfkdSweepCase is a `[code_point, slug("a"+chr(cp)+"b")]` pair.
type nfkdSweepCase struct {
	CodePoint rune
	Slug      string
}

func (c *nfkdSweepCase) UnmarshalJSON(data []byte) error {
	var raw [2]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if err := json.Unmarshal(raw[0], &c.CodePoint); err != nil {
		return err
	}
	return json.Unmarshal(raw[1], &c.Slug)
}

type hrbCase struct {
	Size   string `json:"size"`
	Output string `json:"output"`
	Error  string `json:"error"`
}

type versionFixture struct {
	CurrentVersion string             `json:"current_version"`
	DockerEngine   []engineCase       `json:"docker_engine"`
	Parse          []versionParseCase `json:"parse"`
	LessThan       []lessThanCase     `json:"less_than"`
}

type engineCase struct {
	Input  string `json:"input"`
	Output string `json:"output"`
	Error  string `json:"error"`
}

type versionParseCase struct {
	Input string `json:"input"`
	Parts []int  `json:"parts"`
	Error string `json:"error"`
}

type lessThanCase struct {
	A        string `json:"a"`
	B        string `json:"b"`
	LessThan bool   `json:"less_than"`
	Error    string `json:"error"`
}

type archFixture struct {
	HostMachine string     `json:"host_machine"`
	Cases       []archCase `json:"cases"`
}

type archCase struct {
	Machine string `json:"machine"`
	Output  string `json:"output"`
	Error   string `json:"error"`
}

type cdMacCase struct {
	Input string  `json:"input"`
	CD    string  `json:"cd"`
	Mac   *string `json:"mac"`
	Error string  `json:"error"`
}

type checkVarCase struct {
	Required bool     `json:"required"`
	Names    []string `json:"names"`
	Present  []bool   `json:"present"`
	Error    string   `json:"error"`
}

type reCase struct {
	Expr  string `json:"expr"`
	Line  string `json:"line"`
	Match string `json:"match"`
	Error string `json:"error"`
}

type realpathCase struct {
	Input    string `json:"input"`
	Realpath string `json:"realpath"`
	Output   string `json:"output"`
	Error    string `json:"error"`
}

type permsFixture struct {
	Euid  int         `json:"euid"`
	Cases []permsCase `json:"cases"`
}

type permsCase struct {
	Dir     string   `json:"dir"`
	DirMode int      `json:"dir_mode"`
	Mode    string   `json:"mode"`
	Missing []string `json:"missing"`
	Error   string   `json:"error"`
}

type execCase struct {
	Input  string  `json:"input"`
	Output *string `json:"output"`
}

// whichCase is one `shutil.which` vector. A nil Path means the probe ran with
// PATH removed from the environment, which is not the same as an empty one.
type whichCase struct {
	Cmd    string  `json:"cmd"`
	Path   *string `json:"path"`
	Output *string `json:"output"`
}

type ntpathFixture struct {
	SplitRoot []ntTripleCase `json:"splitroot"`
	Split     []ntTripleCase `json:"split"`
	Join      []ntJoinCase   `json:"join"`
	NormCase  []ntStringCase `json:"normcase"`
}

type ntTripleCase struct {
	Input  string   `json:"input"`
	Output []string `json:"output"`
}

type ntJoinCase struct {
	A      string `json:"a"`
	B      string `json:"b"`
	Output string `json:"output"`
}

type ntStringCase struct {
	Input  string `json:"input"`
	Output string `json:"output"`
}

var (
	fixtureOnce sync.Once
	fixtureData utilsFixture
	fixtureErr  error
)

func loadFixture(t *testing.T) *utilsFixture {
	t.Helper()

	fixtureOnce.Do(func() {
		raw, err := os.ReadFile(filepath.Join("testdata", "utils", "expected.json"))
		if err != nil {
			fixtureErr = err
			return
		}
		fixtureErr = json.Unmarshal(raw, &fixtureData)
	})
	if fixtureErr != nil {
		t.Fatalf("loading testdata/utils/expected.json: %v", fixtureErr)
	}

	return &fixtureData
}

// pythonError strips the `TypeName: ` prefix the probe records so the message
// can be compared against a Go error's text.
func pythonError(recorded string) string {
	_, message, found := strings.Cut(recorded, ": ")
	if !found {
		return ""
	}
	return message
}

// ---------------------------------------------------------------------------
// generate_urlsafe_hash / slug / get_current_user_name
// ---------------------------------------------------------------------------

func TestGenerateURLSafeHash(t *testing.T) {
	for _, tc := range loadFixture(t).URLSafeHash {
		t.Run(tc.Hex, func(t *testing.T) {
			if got := GenerateURLSafeHash(tc.Input); got != tc.Output {
				t.Errorf("GenerateURLSafeHash(%q) = %q, oracle says %q", tc.Input, got, tc.Output)
			}
		})
	}
}

// TestGenerateURLSafeHashStripsHighBytes pins the two properties the table can
// only sample: a non-ASCII run contributes nothing, so any two strings that
// differ only outside ASCII collide, and the C0 controls are inside the kept
// range rather than stripped with them.
func TestGenerateURLSafeHashStripsHighBytes(t *testing.T) {
	if GenerateURLSafeHash("日本語") != GenerateURLSafeHash("") {
		t.Error("a wholly non-ASCII string must hash as the empty string")
	}
	if GenerateURLSafeHash("a日本語b") != GenerateURLSafeHash("ab") {
		t.Error("a non-ASCII run must be deleted, not replaced")
	}
	if GenerateURLSafeHash("\x00\x01\x7f") == GenerateURLSafeHash("") {
		t.Error("ASCII controls are inside [\\x00-\\x7F] and must survive")
	}
}

// TestGenerateURLSafeHashAlphabet pins the shape callers depend on: the result
// is alphanumeric, so it is safe in a container name, a network name and a
// Kubernetes namespace, and it is never the fixed 22 characters of a base64
// digest because '-' and '_' are deleted rather than substituted.
func TestGenerateURLSafeHashAlphabet(t *testing.T) {
	alphanumeric := regexp.MustCompile(`^[A-Za-z0-9]*$`)

	sawShort := false
	for _, tc := range loadFixture(t).URLSafeHash {
		if !alphanumeric.MatchString(tc.Output) {
			t.Errorf("hash of %q is %q, which is not alphanumeric", tc.Input, tc.Output)
		}
		if len(tc.Output) > 22 {
			t.Errorf("hash of %q is %d characters, more than the 22 of a trimmed digest", tc.Input, len(tc.Output))
		}
		if len(tc.Output) < 22 {
			sawShort = true
		}
	}
	if !sawShort {
		t.Error("no vector exercised the shortening effect of deleting '-' and '_'")
	}
}

func TestSlug(t *testing.T) {
	for _, tc := range loadFixture(t).Slug {
		t.Run(tc.Hex, func(t *testing.T) {
			if got := Slug(tc.Input); got != tc.Output {
				t.Errorf("Slug(%q) = %q, oracle says %q", tc.Input, got, tc.Output)
			}
		})
	}
}

// TestSlugNFKDSweep is the parity check between Go's x/text NFKD and CPython's
// unicodedata: every code point above ASCII whose NFKD normalisation yields
// anything ASCII, which is the complete set on which Slug can behave
// differently from a plain "delete non-ASCII".
func TestSlugNFKDSweep(t *testing.T) {
	sweep := loadFixture(t).SlugNFKDSweep
	if len(sweep) < 2000 {
		t.Fatalf("sweep has only %d code points; the fixture looks truncated", len(sweep))
	}

	for _, tc := range sweep {
		input := "a" + string(tc.CodePoint) + "b"
		if got := Slug(input); got != tc.Slug {
			t.Errorf("Slug(%q) with U+%04X = %q, oracle says %q", input, tc.CodePoint, got, tc.Slug)
		}
	}
}

func TestUserNameChain(t *testing.T) {
	for _, tc := range loadFixture(t).UserNameChain {
		t.Run(tc.Username+"@"+tc.Hostname, func(t *testing.T) {
			hash := GenerateURLSafeHash(tc.Hostname)
			if hash != tc.HostnameHash {
				t.Fatalf("hostname hash of %q = %q, oracle says %q", tc.Hostname, hash, tc.HostnameHash)
			}
			if got := Slug(tc.Username + "-" + hash); got != tc.Output {
				t.Errorf("user name for %q@%q = %q, oracle says %q", tc.Username, tc.Hostname, got, tc.Output)
			}
		})
	}
}

// TestUserNameChainIsHostSensitive pins the property the naming scheme exists
// for: the same login on two hosts must not produce the same identity, and a
// hostname that differs only in case must not fold together (the hostname is
// hashed before it is slugged, so the case survives into the digest).
func TestUserNameChainIsHostSensitive(t *testing.T) {
	a := Slug("root" + "-" + GenerateURLSafeHash("kathara-host"))
	b := Slug("root" + "-" + GenerateURLSafeHash("other-host"))
	c := Slug("root" + "-" + GenerateURLSafeHash("KATHARA-HOST"))

	if a == b {
		t.Error("two hosts produced the same user name")
	}
	if a == c {
		t.Error("hostname case must reach the digest, so it must change the user name")
	}
}

// ---------------------------------------------------------------------------
// human_readable_bytes
// ---------------------------------------------------------------------------

func TestHumanReadableBytes(t *testing.T) {
	for _, tc := range loadFixture(t).HumanReadableBytes {
		t.Run(tc.Size, func(t *testing.T) {
			size, err := strconv.ParseInt(tc.Size, 10, 64)
			if err != nil {
				t.Fatalf("fixture size %q: %v", tc.Size, err)
			}

			got, err := HumanReadableBytes(size)
			if tc.Error != "" {
				if err == nil {
					t.Fatalf("HumanReadableBytes(%d) = %q, oracle raised %s", size, got, tc.Error)
				}
				if err.Error() != pythonError(tc.Error) {
					t.Errorf("HumanReadableBytes(%d) error = %q, oracle says %q", size, err, pythonError(tc.Error))
				}
				if !errors.Is(err, kerrors.ErrValue) {
					t.Errorf("HumanReadableBytes(%d) error is not classified Value", size)
				}
				return
			}
			if err != nil {
				t.Fatalf("HumanReadableBytes(%d): %v", size, err)
			}
			if got != tc.Output {
				t.Errorf("HumanReadableBytes(%d) = %q, oracle says %q", size, got, tc.Output)
			}
		})
	}
}

// TestHumanReadableBytesBulk is the 2,900-value sweep: every 2**k
// neighbourhood plus a seeded random sample. It is what catches a rounding
// mode or a float-repr difference that the hand-picked table would miss.
func TestHumanReadableBytesBulk(t *testing.T) {
	bulk := loadFixture(t).HumanReadableBytesBulk
	if len(bulk) < 2000 {
		t.Fatalf("bulk sweep has only %d values; the fixture looks truncated", len(bulk))
	}

	for _, tc := range bulk {
		size, err := strconv.ParseInt(tc[0], 10, 64)
		if err != nil {
			t.Fatalf("fixture size %q: %v", tc[0], err)
		}
		got, err := HumanReadableBytes(size)
		if err != nil {
			t.Fatalf("HumanReadableBytes(%d): %v", size, err)
		}
		if got != tc[1] {
			t.Errorf("HumanReadableBytes(%d) = %q, oracle says %q", size, got, tc[1])
		}
	}
}

// TestHumanReadableBytesFloatRepr pins the two shapes the format has to keep:
// an integral value prints with a ".0" that Go's %v would drop, and the
// exponent is picked before the rounding so a value just under a power comes
// out as "1024.0 KB" and never as "1.0 MB".
func TestHumanReadableBytesFloatRepr(t *testing.T) {
	for _, tc := range []struct {
		size int64
		want string
	}{
		{0, "0 B"},
		{1, "1.0 B"},
		{1024, "1.0 KB"},
		{1048575, "1024.0 KB"},
		{1048576, "1.0 MB"},
		{10000, "9.77 KB"},
		// float(2**50-1)/float(2**50) rounds to exactly 1.0, selecting the next
		// unit in Python.
		{1125899906842623, "1.0 PB"},
	} {
		got, err := HumanReadableBytes(tc.size)
		if err != nil {
			t.Fatalf("HumanReadableBytes(%d): %v", tc.size, err)
		}
		if got != tc.want {
			t.Errorf("HumanReadableBytes(%d) = %q, want %q", tc.size, got, tc.want)
		}
	}
}

// ---------------------------------------------------------------------------
// version.py + parse_docker_engine_version
// ---------------------------------------------------------------------------

func TestCurrentVersion(t *testing.T) {
	fixture := loadFixture(t)
	if CurrentVersion != fixture.Version.CurrentVersion {
		t.Errorf("CurrentVersion = %q, oracle says %q", CurrentVersion, fixture.Version.CurrentVersion)
	}
	if CurrentVersion != fixture.KatharaVersion {
		t.Errorf("CurrentVersion = %q, fixture was generated against %q", CurrentVersion, fixture.KatharaVersion)
	}
}

func TestParseDockerEngineVersion(t *testing.T) {
	for _, tc := range loadFixture(t).Version.DockerEngine {
		t.Run(tc.Input, func(t *testing.T) {
			if tc.Error != "" {
				t.Fatalf("fixture records an error for %q, which the char loop cannot raise: %s", tc.Input, tc.Error)
			}
			if got := ParseDockerEngineVersion(tc.Input); got != tc.Output {
				t.Errorf("ParseDockerEngineVersion(%q) = %q, oracle says %q", tc.Input, got, tc.Output)
			}
		})
	}
}

// TestParseDockerEngineVersionQuirks names the two behaviours that make the
// character loop worth copying instead of replacing with a regexp, both
// sampled by the table above.
func TestParseDockerEngineVersionQuirks(t *testing.T) {
	// A part keeps its leading digit run and the loop continues, so a
	// pre-release suffix is not truncated at — it is deleted from the middle,
	// and the parts behind it move up.
	if got := ParseDockerEngineVersion("20.10-beta.3"); got != "20.10.3" {
		t.Errorf("ParseDockerEngineVersion(\"20.10-beta.3\") = %q, want \"20.10.3\"", got)
	}
	// A part with no leading digit stops the loop outright, so a leading "v"
	// or a leading space empties the whole version.
	for _, input := range []string{"v20.10.14", " 1.2", "abc"} {
		if got := ParseDockerEngineVersion(input); got != "" {
			t.Errorf("ParseDockerEngineVersion(%q) = %q, want \"\"", input, got)
		}
	}
	// str.isdigit() is wider than int() accepts, which is observable exactly
	// here: the superscript survives the sanitiser and then fails the parse.
	if got := ParseDockerEngineVersion("1².2"); got != "1².2" {
		t.Errorf("ParseDockerEngineVersion(\"1².2\") = %q, want \"1².2\"", got)
	}
	if _, err := ParseVersion("1².2"); err == nil {
		t.Error("ParseVersion must reject the superscript ParseDockerEngineVersion keeps")
	}
}

func TestParseVersion(t *testing.T) {
	for _, tc := range loadFixture(t).Version.Parse {
		t.Run(tc.Input, func(t *testing.T) {
			got, err := ParseVersion(tc.Input)

			if tc.Error != "" {
				if err == nil {
					t.Fatalf("ParseVersion(%q) = %v, oracle raised %s", tc.Input, got, tc.Error)
				}
				if err.Error() != pythonError(tc.Error) {
					t.Errorf("ParseVersion(%q) error = %q, oracle says %q", tc.Input, err, pythonError(tc.Error))
				}
				if !errors.Is(err, kerrors.ErrValue) {
					t.Errorf("ParseVersion(%q) error is not classified Value", tc.Input)
				}
				return
			}
			if err != nil {
				t.Fatalf("ParseVersion(%q): %v", tc.Input, err)
			}
			if len(got) != len(tc.Parts) {
				t.Fatalf("ParseVersion(%q) = %v, oracle says %v", tc.Input, got, tc.Parts)
			}
			for i := range got {
				if got[i] != tc.Parts[i] {
					t.Fatalf("ParseVersion(%q) = %v, oracle says %v", tc.Input, got, tc.Parts)
				}
			}
		})
	}
}

func TestLessThan(t *testing.T) {
	for _, tc := range loadFixture(t).Version.LessThan {
		t.Run(tc.A+"<"+tc.B, func(t *testing.T) {
			got, err := LessThan(tc.A, tc.B)

			if tc.Error != "" {
				if err == nil {
					t.Fatalf("LessThan(%q, %q) = %v, oracle raised %s", tc.A, tc.B, got, tc.Error)
				}
				if err.Error() != pythonError(tc.Error) {
					t.Errorf("LessThan(%q, %q) error = %q, oracle says %q", tc.A, tc.B, err, pythonError(tc.Error))
				}
				return
			}
			if err != nil {
				t.Fatalf("LessThan(%q, %q): %v", tc.A, tc.B, err)
			}
			if got != tc.LessThan {
				t.Errorf("LessThan(%q, %q) = %v, oracle says %v", tc.A, tc.B, got, tc.LessThan)
			}
		})
	}
}

// TestLessThanIsTupleComparison pins the rule that makes this not a semver
// compare: a prefix is smaller than what extends it, so 3.8 < 3.8.1 and
// 0 < 0.0, and a component is compared numerically so 3.9 < 3.10.
func TestLessThanIsTupleComparison(t *testing.T) {
	for _, tc := range []struct {
		a, b string
		want bool
	}{
		{"3.8", "3.8.1", true},
		{"3.8.1", "3.8", false},
		{"0", "0.0", true},
		{"0.0", "0", false},
		{"3.9", "3.10", true},
		{"3.10", "3.9", false},
		{"007.008", "7.8", false},
		{"7.8", "007.008", false},
	} {
		got, err := LessThan(tc.a, tc.b)
		if err != nil {
			t.Fatalf("LessThan(%q, %q): %v", tc.a, tc.b, err)
		}
		if got != tc.want {
			t.Errorf("LessThan(%q, %q) = %v, want %v", tc.a, tc.b, got, tc.want)
		}
	}
}

// ---------------------------------------------------------------------------
// get_architecture
// ---------------------------------------------------------------------------

func TestArchitectureOf(t *testing.T) {
	for _, tc := range loadFixture(t).Architecture.Cases {
		t.Run(tc.Machine, func(t *testing.T) {
			got, err := architectureOf(tc.Machine)

			if tc.Error != "" {
				if err == nil {
					t.Fatalf("architectureOf(%q) = %q, oracle raised %s", tc.Machine, got, tc.Error)
				}
				if err.Error() != pythonError(tc.Error) {
					t.Errorf("architectureOf(%q) error = %q, oracle says %q", tc.Machine, err, pythonError(tc.Error))
				}
				var hostErr *kerrors.HostArchError
				if !errors.As(err, &hostErr) {
					t.Fatalf("architectureOf(%q) error is not a HostArchError", tc.Machine)
				}
				if hostErr.Arch != strings.ToLower(tc.Machine) {
					t.Errorf("HostArchError.Arch = %q, want the lower-cased %q", hostErr.Arch, tc.Machine)
				}
				return
			}
			if err != nil {
				t.Fatalf("architectureOf(%q): %v", tc.Machine, err)
			}
			if got != tc.Output {
				t.Errorf("architectureOf(%q) = %q, oracle says %q", tc.Machine, got, tc.Output)
			}
		})
	}
}

// TestGetArchitectureReadsTheKernel pins that the value comes from uname and
// not from this binary: it must agree with what the oracle read from the same
// host, which a GOARCH-derived answer would only do by coincidence.
func TestGetArchitectureReadsTheKernel(t *testing.T) {
	fixture := loadFixture(t)

	machine := machineName()
	if machine != fixture.Architecture.HostMachine {
		t.Skipf("fixture recorded machine %q, this host reports %q",
			fixture.Architecture.HostMachine, machine)
	}

	got, err := GetArchitecture()
	if err != nil {
		t.Fatalf("GetArchitecture: %v", err)
	}
	if got != fixture.Live.Architecture {
		t.Errorf("GetArchitecture() = %q, oracle says %q", got, fixture.Live.Architecture)
	}
}

// ---------------------------------------------------------------------------
// parse_cd_mac_address
// ---------------------------------------------------------------------------

func TestParseCDMACAddress(t *testing.T) {
	for _, tc := range loadFixture(t).CDMac {
		t.Run(tc.Input, func(t *testing.T) {
			cd, mac, err := ParseCDMACAddress(tc.Input)

			if tc.Error != "" {
				if err == nil {
					t.Fatalf("ParseCDMACAddress(%q) = (%q, %q), oracle raised %s", tc.Input, cd, mac, tc.Error)
				}
				if err.Error() != pythonError(tc.Error) {
					t.Errorf("ParseCDMACAddress(%q) error = %q, oracle says %q", tc.Input, err, pythonError(tc.Error))
				}
				if !errors.Is(err, kerrors.ErrSyntax) {
					t.Errorf("ParseCDMACAddress(%q) error is not classified Syntax", tc.Input)
				}
				return
			}
			if err != nil {
				t.Fatalf("ParseCDMACAddress(%q): %v", tc.Input, err)
			}
			if cd != tc.CD {
				t.Errorf("ParseCDMACAddress(%q) cd = %q, oracle says %q", tc.Input, cd, tc.CD)
			}

			// Python's None becomes the empty string; the other branch can
			// never produce an empty MAC, so the two are not confusable.
			wantMac := ""
			if tc.Mac != nil {
				wantMac = *tc.Mac
			}
			if mac != wantMac {
				t.Errorf("ParseCDMACAddress(%q) mac = %q, oracle says %q", tc.Input, mac, wantMac)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// check_single_not_none_var / check_required_single_not_none_var
// ---------------------------------------------------------------------------

func TestCheckNotNoneVars(t *testing.T) {
	for _, tc := range loadFixture(t).CheckVars {
		name := strings.Join(tc.Names, ",")
		if tc.Required {
			name = "required/" + name
		}

		t.Run(name, func(t *testing.T) {
			params := make([]Param, 0, len(tc.Names))
			for i, paramName := range tc.Names {
				params = append(params, Param{Name: paramName, Present: tc.Present[i]})
			}

			var err error
			if tc.Required {
				err = CheckRequiredSingleNotNoneVar(params...)
			} else {
				err = CheckSingleNotNoneVar(params...)
			}

			if tc.Error == "" {
				if err != nil {
					t.Fatalf("unexpected error: %v", err)
				}
				return
			}
			if err == nil {
				t.Fatalf("no error, oracle says %q", tc.Error)
			}
			if err.Error() != tc.Error {
				t.Errorf("error = %q, oracle says %q", err, tc.Error)
			}
			if !errors.Is(err, kerrors.ErrInvocation) {
				t.Error("error is not classified Invocation")
			}
		})
	}
}

func TestCheckNotNoneVarsKeepsCallOrder(t *testing.T) {
	params := []Param{
		{Name: "lab_hash", Present: true},
		{Name: "lab_name", Present: true},
		{Name: "lab", Present: false},
	}

	err := CheckSingleNotNoneVar(params...)
	if err == nil {
		t.Fatal("two supplied parameters must be an error")
	}
	if err.Error() != "You must specify only a parameter among lab_hash, lab_name, lab" {
		t.Errorf("error = %q", err)
	}

	reversed := []Param{params[2], params[1], params[0]}
	err = CheckSingleNotNoneVar(reversed...)
	if err == nil {
		t.Fatal("two supplied parameters must be an error")
	}
	if err.Error() != "You must specify only a parameter among lab, lab_name, lab_hash" {
		t.Errorf("reordered call site must reorder the message, got %q", err)
	}
}

// ---------------------------------------------------------------------------
// re_search_fail
// ---------------------------------------------------------------------------

// goRegexpFor translates the one pattern re_search_fail is called with
// (Setting.py:216,221) into RE2. Python's `$` also matches immediately before
// a trailing newline; Go's does not without `(?m)`, which would also change
// `^`, so the newline is spelled out instead.
func goRegexpFor(pythonPattern string) string {
	return strings.TrimSuffix(pythonPattern, "$") + `\n?$`
}

func TestReSearchFail(t *testing.T) {
	for _, tc := range loadFixture(t).ReSearchFail {
		t.Run(tc.Expr+"/"+strconv.Quote(tc.Line), func(t *testing.T) {
			expression := regexp.MustCompile(goRegexpFor(tc.Expr))

			matches, err := ReSearchFail(expression, tc.Line)

			if tc.Error != "" {
				if err == nil {
					t.Fatalf("ReSearchFail(%q) = %v, oracle raised %s", tc.Line, matches, tc.Error)
				}
				if !errors.Is(err, ErrNoMatch) {
					t.Errorf("error is %v, want ErrNoMatch", err)
				}
				return
			}
			if err != nil {
				t.Fatalf("ReSearchFail(%q): %v", tc.Line, err)
			}
			if len(matches) == 0 {
				t.Fatal("a successful search must return at least group 0")
			}
			// The translated pattern absorbs the trailing newline that
			// Python's `$` merely allows, so group 0 can be one byte longer.
			if strings.TrimSuffix(matches[0], "\n") != tc.Match {
				t.Errorf("group 0 = %q, oracle says %q", matches[0], tc.Match)
			}
		})
	}
}

// TestReSearchFailNeedsTheNewlineSpelledOut is the reason goRegexpFor exists:
// the untranslated pattern disagrees with Python on exactly one of the
// fixture's lines, and silently — it rejects a settings value Python accepts.
func TestReSearchFailNeedsTheNewlineSpelledOut(t *testing.T) {
	literal := regexp.MustCompile(`^[a-z]+_?[a-z_]+$`)

	if _, err := ReSearchFail(literal, "kathara\n"); !errors.Is(err, ErrNoMatch) {
		t.Fatal("RE2's `$` is end-of-text; the literal pattern must reject a trailing newline")
	}

	translated := regexp.MustCompile(goRegexpFor(`^[a-z]+_?[a-z_]+$`))
	if _, err := ReSearchFail(translated, "kathara\n"); err != nil {
		t.Fatalf("the translated pattern must accept it, as Python does: %v", err)
	}
	if _, err := ReSearchFail(translated, "kathara\nnope"); !errors.Is(err, ErrNoMatch) {
		t.Fatal("the newline must only be allowed at the very end")
	}
}

// ---------------------------------------------------------------------------
// Module constants and the live identity
// ---------------------------------------------------------------------------

func TestModuleConstants(t *testing.T) {
	fixture := loadFixture(t)

	if got := ReservedMachineNames(); !equalStrings(got, fixture.Live.ReservedMachineNames) {
		t.Errorf("ReservedMachineNames() = %v, oracle says %v", got, fixture.Live.ReservedMachineNames)
	}
	if got := ExcludedFiles(); !equalStrings(got, fixture.Live.ExcludedFiles) {
		t.Errorf("ExcludedFiles() = %v, oracle says %v", got, fixture.Live.ExcludedFiles)
	}

	for _, name := range fixture.Live.ReservedMachineNames {
		if !IsReservedMachineName(name) {
			t.Errorf("IsReservedMachineName(%q) = false", name)
		}
		if IsReservedMachineName(strings.ToUpper(name)) {
			t.Errorf("IsReservedMachineName is `in` on a list: %q must not match", strings.ToUpper(name))
		}
	}
	if IsReservedMachineName("pc1") {
		t.Error("IsReservedMachineName(\"pc1\") = true")
	}
}

// TestConstantAccessorsCopy pins that a caller cannot mutate the package's
// state through the returned slice.
func TestConstantAccessorsCopy(t *testing.T) {
	first := ReservedMachineNames()
	first[0] = "clobbered"

	if second := ReservedMachineNames(); second[0] != "shared" {
		t.Errorf("ReservedMachineNames() returned an aliased slice: %v", second)
	}
}

// TestLiveIdentity compares the whole identity chain against what the oracle
// observed on this host. It is skipped when the fixture was generated
// somewhere else, since none of these values are portable; the byte-exactness
// of the chain itself is pinned by the tables above, which are.
func TestLiveIdentity(t *testing.T) {
	fixture := loadFixture(t)

	if nodeName() != fixture.Live.Node || os.Getuid() != fixture.Live.OsGetuid {
		t.Skipf("fixture was recorded on %q as uid %d; this is %q as uid %d",
			fixture.Live.Node, fixture.Live.OsGetuid, nodeName(), os.Getuid())
	}

	info, err := GetCurrentUserInfo()
	if err != nil {
		t.Fatalf("GetCurrentUserInfo: %v", err)
	}
	if info.Name != fixture.Live.PwName {
		t.Errorf("pw_name = %q, oracle says %q", info.Name, fixture.Live.PwName)
	}
	if info.UID != fixture.Live.PwUID {
		t.Errorf("pw_uid = %d, oracle says %d", info.UID, fixture.Live.PwUID)
	}
	if info.GID != fixture.Live.PwGID {
		t.Errorf("pw_gid = %d, oracle says %d", info.GID, fixture.Live.PwGID)
	}
	if info.HomeDir != fixture.Live.PwDir {
		t.Errorf("pw_dir = %q, oracle says %q", info.HomeDir, fixture.Live.PwDir)
	}

	uid, gid, err := GetCurrentUserUIDGID()
	if err != nil {
		t.Fatalf("GetCurrentUserUIDGID: %v", err)
	}
	if uid != fixture.Live.UID || gid != fixture.Live.GID {
		t.Errorf("uid/gid = %d/%d, oracle says %d/%d", uid, gid, fixture.Live.UID, fixture.Live.GID)
	}

	name, err := GetCurrentUserName()
	if err != nil {
		t.Fatalf("GetCurrentUserName: %v", err)
	}
	if name != fixture.Live.CurrentUserName {
		t.Errorf("GetCurrentUserName() = %q, oracle says %q", name, fixture.Live.CurrentUserName)
	}

	home, err := GetCurrentUserHome()
	if err != nil {
		t.Fatalf("GetCurrentUserHome: %v", err)
	}
	if home != fixture.Live.CurrentUserHome {
		t.Errorf("GetCurrentUserHome() = %q, oracle says %q", home, fixture.Live.CurrentUserHome)
	}

	admin, err := IsAdmin()
	if err != nil {
		t.Fatalf("IsAdmin: %v", err)
	}
	if admin != fixture.Live.IsAdmin {
		t.Errorf("IsAdmin() = %v, oracle says %v", admin, fixture.Live.IsAdmin)
	}

	if got := IsWSLPlatform(); got != fixture.Live.IsWSL {
		t.Errorf("IsWSLPlatform() = %v, oracle says %v", got, fixture.Live.IsWSL)
	}
}

// TestGetCurrentUserNameComposesTheChain pins the composition itself, on any
// host: the name is slug(login + "-" + hash(node)), with the hostname hashed
// and the login not.
func TestGetCurrentUserNameComposesTheChain(t *testing.T) {
	login := ""
	if info, err := GetCurrentUserInfo(); err == nil {
		login = info.Name
	} else if errors.Is(err, ErrNoPasswdDatabase) {
		// The Windows arm has no passwd database (Python's `lambda: None`);
		// the login comes from getpass's env chain instead. Pin the chain by
		// planting its first variable and asserting the composition uses it.
		t.Setenv("LOGNAME", "chainuser")
		login = "chainuser"
	} else {
		t.Fatalf("GetCurrentUserInfo: %v", err)
	}

	got, err := GetCurrentUserName()
	if err != nil {
		t.Fatalf("GetCurrentUserName: %v", err)
	}

	want := Slug(login + "-" + GenerateURLSafeHash(nodeName()))
	if got != want {
		t.Errorf("GetCurrentUserName() = %q, want %q", got, want)
	}
}

func TestPoolSizeIsPositive(t *testing.T) {
	// cpu_count() and runtime.NumCPU() can legitimately differ under a
	// cpuset, so only the property every caller relies on is asserted.
	if PoolSize() < 1 {
		t.Errorf("PoolSize() = %d", PoolSize())
	}
}

// ---------------------------------------------------------------------------
// exec_by_platform
// ---------------------------------------------------------------------------

// TestExecByPlatformArgumentOrder pins the argument order, which is the only
// thing about this function that can go wrong and the thing that would go
// wrong silently: three same-typed function arguments mean the compiler cannot
// catch a swap, and half the Python call sites are asymmetric.
func TestExecByPlatformArgumentOrder(t *testing.T) {
	got := ExecByPlatform(
		func() string { return Linux },
		func() string { return Windows },
		func() string { return MacOS },
	)

	if got != runtime.GOOS {
		t.Errorf("ExecByPlatform picked %q on %q", got, runtime.GOOS)
	}
}

// TestExecByPlatformCallsOneArm pins that the unselected arms are never
// evaluated: several Python call sites pass functions that import a
// platform-only module or touch a platform-only API.
func TestExecByPlatformCallsOneArm(t *testing.T) {
	calls := 0
	count := func() func() int {
		return func() int { calls++; return calls }
	}

	ExecByPlatform(count(), count(), count())

	if calls != 1 {
		t.Errorf("%d arms were evaluated, want 1", calls)
	}
}

func equalStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
